package com.workplat.englishpulish.data.preload

import kotlinx.serialization.Serializable

/**
 * Shape of one entry in assets/preload.json. Generated by scripts/build_preload.py.
 *
 * `level` is one of "gaozhong" | "kaoyan" | "both" and is stored on the row
 * (under WordEntity.source as "preload-<level>") so we can later filter by source.
 */
@Serializable
data class PreloadEntry(
    val lemma: String,
    val phonetic: String? = null,
    val partOfSpeech: String? = null,
    val definitionZh: String,
    val exampleEn: String? = null,
    val exampleZh: String? = null,
    val level: String,
)
